relativeURLS=true
publishdir="docs"
languageCode = "en-uk"
title = "Chenfu's personal page"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "Chenfu Shi"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Chenfu Shi's personal page"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/figure_1.png"]

    [params.meta]
        keywords = "Chenfu, Chenfu Shi, Chromatin interactions, Epigenomics, Bioinformatics, Deep learning, Machine learning, HiC, Hi-C"

[Author]
    name = "Chenfu"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true